### ISSUE TITLE
Help Wanted!

### ISSUE THREAD

**Issue by sotayamashita** [sotayamashita/awesome-css#107]
Recently,  I do not have time to maintain. It has over 1.1k stars so I would like to keep up to dates for everyone who want to see the awesome list. 

Does anybody want to maintain Awesome CSS?

**Comment by Rishabh04-02** [comment]
I want to help in its maintenance.

**Comment by sotayamashita** [comment]
@Rishabh04-02 Rad! I invited you. Please check it out. https://github.com/sotayamashita/awesome-css/invitations

**Comment by Rishabh04-02** [comment]
@sotayamashita Thanks, for the invitation.

**Comment by sotayamashita** [comment]
@Rishabh04-02 I will add your name to README later.

**Comment by Rishabh04-02** [comment]
Yaa, that's fair enough. As for now I haven't contributed to this repo.

**Comment by Rishabh04-02** [comment]
Should we close this issue now?

**Comment by sotayamashita** [comment]
@Rishabh04-02 You do not have to do it because I would like to invite more people.
