### ISSUE TITLE
Add worth-reading CSS books

### ISSUE THREAD

**Issue by jaykay12** [sotayamashita/awesome-css#115]
Apparently, Some people like reading books more than watching videos, So, I propose to add few names of good reference books for learning CSS as currently this particular aspect is missing in the Awesome CSS. :blush:

**Comment by jaykay12** [comment]
@Rishabh04-02 Wasn't my PR Fair enough to serve the purpose? Later on, with course of time enhancements could have been done :disappointed:

**Comment by Rishabh04-02** [comment]
@jaykay12 I've requested the maintainers that we need a discussions platform, once they respond to it then we can have a discussions there regarding the issues, queries and the development of awesome-css.

**Comment by sotayamashita** [comment]
@jaykay12 We are sorry to feel bad. Recently I have invited members but I do not have rules. 

@Rishabh04-02 What about to create rules for maintainers and first rules will be "We need 2 people approval when we merge PRs" What do you think?

**Comment by Rishabh04-02** [comment]
@sotayamashita This 2 people rule is good :+1: , i agree with it.

**Comment by jaykay12** [comment]
@sotayamashita Its totally cool man!
But yeah, #116 was closed as it was containing books that were published around 5-7 years, so will it be nice if I add a Book section in the Awesome CSS with 1 or 2 popular books only & later on substantial additions to it can be done by other contributors as well. :smile:

@Rishabh04-02 what do you say?

**Comment by troxler** [comment]
Sorry if my comments in the pull request seem harsh.

I'm not sure whether it is better to require two approvals as it also means double the work. In my opinion it is enough to ping other contributors to comment if a pull request is controversial. If a request is closed or merged, you can always step into the discussion (and reopen the request) if you disagree.

----

> so will it be nice if I add a Book section in the Awesome CSS with 1 or 2 popular books only

@jaykay12 sure.
