### ISSUE TITLE
Needed a discussions room

### ISSUE THREAD

**Issue by Rishabh04-02** [sotayamashita/awesome-css#117]
@sotayamashita @troxler We need a discussion platform like gitter.im room OR something like that.
So, that we can talk about awesome-css stuff and where we can ask our queries regarding it.
What do you people say?

**Comment by sotayamashita** [comment]
@Rishabh04-02 

I do not agree to create discussion room because we need to check GitHub issues and chat room. Do we really need to do that? What do you think?

**Comment by Rishabh04-02** [comment]
Yaa, this thing can be a little problematic.
So, what if we create an issue named **Discussion** and use it for the required purpose?

**Comment by troxler** [comment]
I think most discussions can happen directly in the issues or pull requests. If other things have to be discussed, I'm fine with topic-specific issues.

**Comment by Rishabh04-02** [comment]
@troxler Like if one wants to suggest something regarding the repo, one should create an issue for it.
Whereas I'm just suggesting that why not have a dedicated ``Discussion`` issue, It'll be helpful and easy to maintain and refer discussed stuff, if needed.

**Comment by troxler** [comment]
> Like if one wants to suggest something regarding the repo, one should create an issue for it.

That is what I'm suggesting. Having a consolidated "Discussion" issue might become overwhelming very soon as you cannot archive older discussions.

**Comment by Rishabh04-02** [comment]
@troxler yaa you are right, okay then we'll go with your idea.

> I think most discussions can happen directly in the issues or pull requests. If other things have to be discussed, I'm fine with topic-specific issues.
