### ISSUE TITLE
Update travis CI

### ISSUE THREAD

**Issue by Rishabh04-02** [sotayamashita/awesome-css#127]
Integrate awesome_bot with Danger and have results reported back to the pull request.

For reference 
1. [awesome_bot danger documentation](https://github.com/dkhamsing/awesome_bot#danger)
2. [Sample travis CI](https://github.com/vsouza/awesome-ios/blob/master/.travis.yml)

**Comment by yamilurbina** [comment]
Hi @Rishabh04-02, this looks simple to implement. Can I give it a go?

**Comment by Rishabh04-02** [comment]
@yamilurbina Its simple, sure you can try it.
