### ISSUE TITLE
I just added Code Sponsor to know how it works.

### ISSUE THREAD

**Issue by sotayamashita** [sotayamashita/awesome-css#132]
> How does Code Sponsor work?

It will show ad on README and if user click the ad, I will get money from Code Sponsor. 

> Do you only get money???? 

This repository is built with great maintainers. So I will share the status once a month and I will share the revenue. :100: , if you guys trust me :bow:

What do you think? :thinking:

- **updated**: I am asking Code Sponsor. _"Is there any API to get current status?"_ now

**Comment by Rishabh04-02** [comment]
Yaa this code sponsor can be added to the repo and it doesn't create distractions in the main content file.
So, I think its good to go with it.
![screenshot from 2017-10-24 23-18-55](https://user-images.githubusercontent.com/12505795/31959242-af8280f4-b8e3-11e7-8f48-a290fc461dd6.png)

**Comment by sotayamashita** [comment]
Wow. I have earned $0.40 so far. ✨

**Comment by troxler** [comment]
This is fine for me. I'm especially interested to know if and how well this works :)

**Comment by Rishabh04-02** [comment]
As we all agree for using Code sponsor then, lets keep going with it.

**Comment by troxler** [comment]
I would've expected more impressions, but those numbers are in line with [the visitor numbers provided by GitHub](https://github.com/sotayamashita/awesome-css/graphs/traffic).

**Comment by sotayamashita** [comment]
I closed the issue because there is not code sponsor :cry:.
