### ISSUE TITLE
Reset/Normalize: + unstyle.css?

### ISSUE THREAD

**Issue by Martin-Pitt** [sotayamashita/awesome-css#34]
I'd like to have 'unstyle.css'/'css-unstyle' added if OK.

Disclaimer: I am the creator. I do think this is unique and have always wanted something like this as a frontend developer.
Git Repo: https://github.com/Martin-Pitt/css-unstyle

Based on guidelines for contributing it does meet two requirements:
(c) absolutely unique in its approach and function
(d) a niche product that fills a gap

Granted however it is not:
- widely discussed
- known about
- established as best practice (yet?)

Unlike reset/normalize which seek to remove or stabilise browser inconsistencies/styling, unstyle.css instead:
- fights back against user agent styling opinions
- unstyling elements down to barebones

However, it is not all-encompassing: I did skip 'input' unstyling as there are harsh browser limitations with css on those; Which would otherwise make unstyle.css too opinionated by itself, as the point is in removing the opinion of the user agent after all.

Thus the goal of unstyle.css:
- remove user agent opinion
- give you peace of mind as to how you can paint the canvas, so to speak

I have used it in many real world production projects and has served me well.
Critical feedback/critique is welcome.

**Comment by sotayamashita** [comment]
It looks good. If you create PR, I will merge
