### ISSUE TITLE
Add styleguide generator

### ISSUE THREAD

**Issue by sotayamashita** [sotayamashita/awesome-css#49]

**Comment by Gurylev** [comment]
* [Source](https://sourcejs.com/) is a dynamic Style Guide platform. It allows to combine multiple project UI component libraries, based on any technologies.
* [mdcss](https://github.com/jonathantneal/mdcss) lets you easily create and maintain style guides with CSS comments using Markdown.
* [StyleDoc](http://usestyledoc.org/) - format specification for JavaDoc-like comments in CSS, LESS, SASS etc.

**Comment by martinpesout** [comment]
+1 adding this to Awesome CSS list.

**Comment by sotayamashita** [comment]
@Gurylev Thank you suggesting me!

**Comment by sotayamashita** [comment]
https://github.com/straker/css-style-guide-audit
