### ISSUE TITLE
Update `must-watch-css`

### ISSUE THREAD

**Issue by arthurvr** [sotayamashita/awesome-css#8]
To adopt the more recent talks added to `must-watch-css`. 

Side: I think it's strange that you're just replicating the content on that list here. Might as well just link up the other repo. That would make it more maintainable and from the user standpoint doesn't have any disadvantages.

**Comment by sotayamashita** [comment]
@arthurvr OK I try to write some video urls



> Side: I think it's strange that you're just replicating the content on that list here. Might as well just link up the other repo. That would make it more maintainable and from the user standpoint doesn't have any disadvantages.

I'll fix it.

**Comment by sotayamashita** [comment]
I would like to ask everyone how to detect whether talk is good or not
